name: Maven Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.7
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: PRIVATE_KEY_PASSPHRASE

      - name: Publish package
        run: mvn clean deploy
        env:
          SONATYPE_USERNAME: 'uncloudedvm@gmail.com'
          SONATYPE_PASSWORD: ${{ secret.SONATYPE_PASSWORD }}
          PRIVATE_KEY_PASSPHRASE: ${{ secret.PRIVATE_KEY_PASSPHRASE }}
