name: Maven Package

on:
  push:
    tags: v*.*

jobs:
  build:
    if: github.repository == 'braginxv/netgym' && github.actor == 'braginxv'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.7
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.KEYSTORE }}
          gpg-passphrase: PRIVATE_KEY_PASSPHRASE

      - name: Publish package
        run: mvn clean deploy
        env:
          SONATYPE_USERNAME: 'braginxv'
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PRIVATE_KEY_PASSPHRASE: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
