name: Maven Package

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setup-java@v1
        with:
          java-version: 1.7

      - name: Run tests
        run: mvn test
